### ISSUE TITLE
":..:DependentProject" not supported in settings.gradle

### ISSUE THREAD

**Issue by thomasnield** [spring-projects/eclipse-integration-gradle#90] opened 2015-05-05 14:37 UTC
It seems Eclipse does not like the settings.gradle file using ".." in project dependency paths. It works fine on the command line and IDEA, but Eclipse throws an error that seems to misinterpret the ".." as a literal folder, not a relative one. I really need this to work for my Gradle setup. 

Here is my StackOverflow post detailing the issue. 
http://stackoverflow.com/questions/29990536/gradle-and-eclipse-dependentproject-not-supported-in-settings-gradle

**Comment by kdvolder** [comment] 2015-05-05 19:43
Duplicate of https://issuetracker.springsource.com/browse/STS-4114

**Closed by kdvolder** 2015-05-05 19:43 UTC
